### ISSUE TITLE
008802 sqlparse format pretty high cpu usage

### ISSUE THREAD

**Issue by shamis** [K2InformaticsGmbH/sqlparse#135]
`sqlparse_format_pretty:break_line_point/6` takes a long time and is getting called repeatedly.

following are screenshots from observer

![image](https://user-images.githubusercontent.com/3499591/40131280-d8005492-5939-11e8-8f26-87f79edbc20e.png)

![image](https://user-images.githubusercontent.com/3499591/40131294-dd14f53c-5939-11e8-9f2f-2259188b5da3.png)

**Comment by stoch** [comment]
@walter-weinmann Kannst du das mal anschauen? Ich glaube, wir haben da einen endless-loop.

**Comment by c-bik** [comment]
@shamis / @stoch can we figure out for which SQL query is this happening? I don't see enough information in the issue description to start a debug!

**Comment by walter-weinmann** [comment]
Solved and new test case added.
