### ISSUE TITLE
`CONSTRAINT` not supported in CREATE TABLE

### ISSUE THREAD

**Issue by c-bik** [K2InformaticsGmbH/sqlparse#137]
```sql
CREATE TABLE
    TPAC_UMJTT (
        cko VARCHAR2(4000),
        chs VARCHAR2(10),
        jpo VARCHAR2(4000),
        tsp DATE,
        ckt VARCHAR2(100),
        cvt VARCHAR2(10),
        cvl VARCHAR2(4000),
        jky VARCHAR2(100),
        rdi CHAR(1),
        hnt VARCHAR2(100),
        CONSTRAINT t_pk PRIMARY KEY (cko, chs, jpo)
    )
```
```erlang
{parse_error,{"13: syntax error before: 'PRIMARY'",

[{'CREATE',1},{'TABLE',1},{'NAME',10,"TPAC_UMJTT"},{'(',2},{'NAME',3,"cko"},
{'NAME',8,"VARCHAR2"},{'(',3},{'INTNUM',3,"4000"},{')',3},{',',3},{'NAME',3,"chs"},
{'NAME',8,"VARCHAR2"},{'(',4},{'INTNUM',4,"10"},{')',4},{',',4},{'NAME',3,"jpo"},
{'NAME',8,"VARCHAR2"},{'(',5},{'INTNUM',5,"4000"},{')',5},{',',5},{'NAME',3,"tsp"},
{'NAME',4,"DATE"},{',',6},{'NAME',3,"ckt"},{'NAME',8,"VARCHAR2"},{'(',7},
{'INTNUM',7,"100"},{')',7},{',',7},{'NAME',3,"cvt"},{'NAME',8,"VARCHAR2"},
{'(',8},{'INTNUM',8,"10"},{')',8},{',',8},{'NAME',3,"cvl"},{'NAME',8,"VARCHAR2"},
{'(',9},{'INTNUM',9,"4000"},{')',9},{',',9},{'NAME',3,"jky"},{'NAME',8,"VARCHAR2"},
{'(',10},{'INTNUM',10,"100"},{')',10},{',',10},{'NAME',3,"rdi"},{'NAME',4,"CHAR"},
{'(',11},{'INTNUM',11,"1"},{')',11},{',',11},{'NAME',3,"hnt"},{'NAME',8,"VARCHAR2"},
{'(',12},{'INTNUM',12,"100"},{')',12},{',',12},{'NAME',10,"CONSTRAINT"},{'NAME',4,"t_pk"},
{'PRIMARY',13},{'KEY',13},{'(',13},{'NAME',3,"cko"},{',',13},{'NAME',3,"chs"},{',',13},
{'NAME',3,"jpo"},{')',13},{')',14},{';',14}]}}}}

[{sqlparse_fold,fold_state_common,4,[{file,"sqlparse/src/sqlparse_fold.erl"},{line,71}]},
{gen_adapter,sql_params,2,[{file,"dderl/src/gen_adapter.erl"},{line,86}]},
{gen_adapter,opt_bind_json_obj,2,[{file,"dderl/src/gen_adapter.erl"},{line,61}]},
{gen_adapter,process_cmd,6,[{file,"dderl/src/gen_adapter.erl"},{line,146}]},
{dderl_session,spawn_gen_process_call,7,[{file,"dderl/src/dderl_session.erl"},{line,643}]}]
```

**Comment by walter-weinmann** [comment]
[SQL Table Constraints 12c.pdf](https://github.com/K2InformaticsGmbH/sqlparse/files/2097638/SQL.Table.Constraints.12c.pdf)

The current grammar definition does not contain any constraints (the keyword CONSTRAINT is not included in the grammar). The attached document shows the current CONSTRAINT definition in the Oracle CREATE TABLE statement. Please make a decision which parts should be included in sqlparse.  

@stoch  @c-bik

**Comment by c-bik** [comment]
Below are the railroad diagrams extracted from @walter-weinmann 's PDF (comment above) for ease of reference to discussion:

This issue is just an observation on current sqlparse support / coverage, please feel free to choose / prioritize betwwen optional paths among the rules to impelment based other projects' need. The projects I am looking at has no requirement for this as of now (workarounds exists). **Perhaps a cosmetic need in DDErl**.

@stoch please decide!

**`constraint::=`**
![image](https://user-images.githubusercontent.com/913008/41344964-aa819b28-6f02-11e8-8945-1506d4c5dc40.png)
**`inline_constraint::=`**
![image](https://user-images.githubusercontent.com/913008/41345023-d4d40d34-6f02-11e8-9057-3a27992c8a04.png)
**`out_of_line_constraint::=`**
![image](https://user-images.githubusercontent.com/913008/41345059-ebb88796-6f02-11e8-93b6-2f1ad68c4988.png)
**`inline_ref_constraint::=`**
![image](https://user-images.githubusercontent.com/913008/41345097-01876ccc-6f03-11e8-9623-a4c0a6719ddf.png)
**`out_of_line_ref_constraint::=`**
![image](https://user-images.githubusercontent.com/913008/41345137-15e160ce-6f03-11e8-8f63-d4e42e60c63f.png)
**`referances_clause::=`**
![image](https://user-images.githubusercontent.com/913008/41345172-31182a26-6f03-11e8-86f6-93541b6b545d.png)
**`constraint_state::=`**
![image](https://user-images.githubusercontent.com/913008/41345198-472f01cc-6f03-11e8-83d5-6ad7214c3932.png)
**`using_index_clause::=`**
![image](https://user-images.githubusercontent.com/913008/41345223-59c3318c-6f03-11e8-9ea3-d016ac7c15c8.png)
**`index_properties::=`**
![image](https://user-images.githubusercontent.com/913008/41345259-6eb0b3f8-6f03-11e8-95e2-b445b30276ce.png)
**`index_attributes::=`**
![image](https://user-images.githubusercontent.com/913008/41345288-7fb6ad2e-6f03-11e8-9bf1-7b16a982ac76.png)
**`exceptions_clause::=`**
![image](https://user-images.githubusercontent.com/913008/41345332-9903845a-6f03-11e8-8542-818d14cbdcdc.png)

**Comment by stoch** [comment]
@walter-weinmann Eventually, in a first step, we might want one way to create foreign keys and constraints as separate statements. In a second step, the convenience of having this inside the create table statement might be added.
For now, these statements are not needed in IMEM. In DDerl for Oracle, the statements should work in spite of the missing parser support.
If that is given, the issue can be put on hold until we have a real need.

**Comment by c-bik** [comment]
@walter-weinmann looks neat! How does the coverage looks like?
