### ISSUE TITLE
GRANT / REVOKE: IDENTIFIED BY

### ISSUE THREAD

**Issue by walter-weinmann** [K2InformaticsGmbH/sqlparse#14]
The `grantee_commalist` and the `grantee` should be different for GRANT and REVOKE, since REVOKE has no `NAME IDENTIFIED BY NAME` clause.

**Comment by c-bik** [comment]
Please provide a parser crash log and/or example SQL

**Comment by walter-weinmann** [comment]
Kline, SQL in a Nutshell (3rd edition):

**Page 273 (GRANT):**

```
GRANT { [object_privilege][, ...] | [system_privilege][, ...] | [role][, ...]
}
[ ON { [schema_name.][object][, ...] |
[DIRECTORY directory_object_name] |
[JAVA [ { SOURCE | RESOURCE } ] [schema_name.][object]] } ]
TO {grantee_name[, ...] | role_name[, ...] | PUBLIC}
[WITH { GRANT | HIERARCHY } OPTION]
[IDENTIFIED BY password] [WITH ADMIN OPTION];
```

**Page 340 (REVOKE):**

In Oracle, use the following syntax with REVOKE:

```
REVOKE { [object_privilege][, ...]|
[system_privilege] |
[role] }
[ON { [schema_name.][object] |
[DIRECTORY directory_object_name] |
[JAVA [ { SOURCE | RESOURCE } ] [schema_name.][object]] } ]
FROM {grantee_name[, ...] | role_name[, ...] | PUBLIC}
[CASCADE [CONSTRAINTS]] [FORCE];

```

**Comment by c-bik** [comment]
I admit that this will pass through some invalid SQL as valid ones (false positive). But for the moment it isn't restricting any valid one (false negative) and which is the primary goal of this parser -- not to validate but to be able generate as much as possible some erlang structure of a given SQL string; validation then relies on the program which will walk the parse-tree structure (IMEM currently).

**Comment by walter-weinmann** [comment]
A possible change would be:

```
revoke_def ->
 REVOKE system_priviledge_list opt_on_obj_clause FROM PUBLIC opt_with_revoke_option  : {'revoke', '$2', '$3', {'from', '$5'}, '$6'}.
revoke_def ->
 REVOKE system_priviledge_list opt_on_obj_clause FROM grantee_revoke_commalist opt_with_revoke_option  : {'revoke', '$2', '$3', {'from', '$5'}, '$6'}.

grantee_revoke_commalist -> NAME                                                                    : ['$1'].
grantee_revoke_commalist -> grantee_revoke_commalist ',' NAME                                              : '$1' ++ ['$3'].
```

If we also consider issue #12.

**Comment by c-bik** [comment]
Thanks @walter-weinmann but....
I general I try to avoid rules changes until there is a valid non-parse-able SQL reported. So I am keeping this issue on hold for now.

**Comment by c-bik** [comment]
It can be reopened on requiement
