### ISSUE TITLE
Datatype problem in IMEM because of uppercase keywords

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/sqlparse#145]
This fails, probably because of uppercase keywords:

![image](https://user-images.githubusercontent.com/1941407/47343579-b2f33a80-d6a6-11e8-9a5e-aa36442def7d.png)

![image](https://user-images.githubusercontent.com/1941407/47343603-c43c4700-d6a6-11e8-94a1-6a968fb16d2a.png)

@walter-weinmann  @acautin 
Can we suppress upper case keywords in dderl for imem?
Should we lowercase keywords in this situation?
Can the error message be improved?

**Comment by acautin** [comment]
@walter-weinmann can correct me if I am wrong but I think there is an option to preserve casing when folding the parsetree, we could add that option to dderl if you think it is a good idea, maybe when the flat option is used. But of course we lose the normalization of the queries.

**Comment by acautin** [comment]
probably related to https://github.com/K2InformaticsGmbH/sqlparse/issues/136

**Comment by walter-weinmann** [comment]
There is an option, please see:

https://github.com/K2InformaticsGmbH/sqlparse/wiki/Formatting-Features

**Comment by walter-weinmann** [comment]
@stoch  & @acautin : can we close this issue ?
