### ISSUE TITLE
REVOKE: FORCE

### ISSUE THREAD

**Issue by walter-weinmann** [K2InformaticsGmbH/sqlparse#15]
#582

FORCE is only used in connection with system_privilege EXECUTE, which is not a valid system_privilege.

**Comment by c-bik** [comment]
Please provide a parser crash log and/or example SQL

**Comment by walter-weinmann** [comment]
I assume that this is adopted from Oracle SQL.

According to Kline, SQL in a Nutshell (3rd edition) on page 341:

FORCE
Required to revoke EXECUTE object privileges on user-defined type objects with
type or table dependencies.

**Comment by walter-weinmann** [comment]
So the change would be:

```
opt_with_revoke_option -> '$empty'                                                              : ''.
opt_with_revoke_option -> CASCADE CONSTRAINS                                                    : 'cascade constrains'.
```

~~opt_with_revoke_option -> FORCE                                                                 : 'force'.~~
