### ISSUE TITLE
Drop View Support

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/sqlparse#158]
If we want to execute multiple SQL statements (separated with SemiColons), they need to be parsable. Otherwise they are given as a whole which will fail in Oracle.

For the upcoming SBS cleanup phase, it would be handy to support most DROP commands (Tables, Views, Packages etc.) in series. 

![image](https://user-images.githubusercontent.com/1941407/53719739-3b58c780-3e5f-11e9-84ca-52e2818992b2.png)

```
sqlparse:parsetree(<<"DROP VIEW SBS1_ADMIN.DT_BIH">>).
{parse_error,{"1: syntax error before: 'VIEW'",
              [{'DROP',1}, 
               {'VIEW',1},
               {'NAME',10,"SBS1_ADMIN"},
               {'.',1},
               {'NAME',6,"DT_BIH"},
               {';',1}]}}
```

**Comment by walter-weinmann** [comment]
Included in version 4.5.0.
