### ISSUE TITLE
Forward slash support

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/sqlparse#159]
Trying to execute multiple CREATE OR REPLACE PACKAGE... statements from one single concatenation text (Ctrl-C on a DDerl Column) provokes problems with forward slashes which usually suffix the create scripts.

What is the real meaning of those?
Why were they invented (probably in SQL-Plus)?
Could we simply ignore them in the parser?
Or do we have to pre-process the sql and eliminate them there (quote-level-counting would be needed)?

**Comment by walter-weinmann** [comment]
Included in version 4.5.0.
