### ISSUE TITLE
SCALAR_OPT_AS_EXPR

### ISSUE THREAD

**Issue by walter-weinmann** [K2InformaticsGmbH/sqlparse#17]
#906 ff.

It should either be `scalar_as_exp` or

`scalar_opt_as-exp -> '$empty'`

is missing.

**Comment by c-bik** [comment]
Please provide a parser crash log and/or example SQL

**Comment by walter-weinmann** [comment]
This is either a confusing name or the empty-clause is missing.

**Comment by walter-weinmann** [comment]
Looking at the parsing file I suppose that

`scalar_opt_as_exp`

should be renamed to

`scalar_as_exp
`

since for example:

```
opt_else -> '$empty'                                                                            : {}.
opt_else -> ELSE scalar_opt_as_exp                                                              : '$2'.
```

would not make much sense if `scalar_opt_as_exp` contains an empty-clause too.
