### ISSUE TITLE
ALTER problems

### ISSUE THREAD

**Issue by walter-weinmann** [K2InformaticsGmbH/sqlparse#21]
The following ALTER statements are not accepted by the parser:

```
ALTER USER name_user_1 GRANT CONNECT THROUGH ENTERPRISE USERS
ALTER USER name_user_1 name_user_2 GRANT CONNECT THROUGH ENTERPRISE USERS
ALTER USER name_user_1 GRANT REVOKE THROUGH ENTERPRISE USERS
ALTER USER name_user_1 REVOKE THROUGH name_user_2

ALTER USER name_user_1 IDENTIFIED BY name_password_1 IDENTIFIED BY name_password_2

ALTER USER name_user_1 DEFAULT ROLE ALL
ALTER USER name_user_1 DEFAULT ROLE ALL EXCEPT name_role_1
ALTER USER name_user_1 DEFAULT ROLE ALL EXCEPT name_role_1 name_role_2
ALTER USER name_user_1 DEFAULT ROLE NONE
ALTER USER name_user_1 DEFAULT ROLE name_role_1
ALTER USER name_user_1 DEFAULT ROLE name_role_1 name_role_2

```

**Comment by c-bik** [comment]
As per grammer [here](http://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_4003.htm)
![image](https://cloud.githubusercontent.com/assets/913008/13775645/fe9be1e8-eaa5-11e5-84b0-eec5506b0c04.png)
![image](https://cloud.githubusercontent.com/assets/913008/13775648/029fad2e-eaa6-11e5-86e5-6d1f006f6131.png)
![image](https://cloud.githubusercontent.com/assets/913008/13775652/09afe264-eaa6-11e5-851b-de40a10bf17b.png)

SQL : `ALTER USER name_user_1 REVOKE THROUGH name_user_2` 
Doesn't look like valid to me. What am I missing?

**Comment by walter-weinmann** [comment]
Those test cases are based on the definitions in the parser file:

**1. Block:**

```
ALTER USER name_user_1 GRANT CONNECT THROUGH ENTERPRISE USERS
ALTER USER name_user_1 name_user_2 GRANT CONNECT THROUGH ENTERPRISE USERS
ALTER USER name_user_1 GRANT REVOKE THROUGH ENTERPRISE USERS
ALTER USER name_user_1 GRANT REVOKE THROUGH name_user_2
```
Reasoning by sqlparse.yrl as follows:

```
alter_user_def -> ALTER USER user_list proxy_clause

proxy_clause -> GRANT CONNECT THROUGH ENTERPRISE USERS 
proxy_clause -> GRANT REVOKE THROUGH ENTERPRISE USERS
proxy_clause -> GRANT REVOKE THROUGH NAME
```

**2. Block:**

```
ALTER USER name_user_1 IDENTIFIED BY name_password_1 IDENTIFIED BY name_password_2
```
Reasoning by sqlparse.yrl as follows:

```
alter_user_def -> ALTER USER NAME spec_list

spec_list -> identified

identified -> IDENTIFIED BY NAME
identified -> IDENTIFIED EXTERNALLY opt_as
identified -> IDENTIFIED GLOBALLY opt_as

opt_as -> '$empty'
opt_as -> AS NAME
```

**3. Block:**

```
ALTER USER name_user_1 DEFAULT ROLE ALL
ALTER USER name_user_1 DEFAULT ROLE ALL EXCEPT name_role_1
ALTER USER name_user_1 DEFAULT ROLE ALL EXCEPT name_role_1 name_role_2
ALTER USER name_user_1 DEFAULT ROLE NONE
ALTER USER name_user_1 DEFAULT ROLE name_role_1
ALTER USER name_user_1 DEFAULT ROLE name_role_1 name_role_2
```
Reasoning by sqlparse.yrl as follows:

```
alter_user_def -> ALTER USER NAME spec_list

spec_list -> user_role

user_role -> DEFAULT ROLE ALL
user_role -> DEFAULT ROLE ALL EXCEPT role_list
user_role -> DEFAULT ROLE NONE
user_role -> DEFAULT ROLE role_list

role_list -> NAME
role_list -> NAME role_list
```

**Comment by c-bik** [comment]
> Reasoning by sqlparse.yrl as follows:
```
alter_user_def -> ALTER USER user_list proxy_clause
proxy_clause -> GRANT CONNECT THROUGH ENTERPRISE USERS 
proxy_clause -> GRANT REVOKE THROUGH ENTERPRISE USERS
proxy_clause -> GRANT REVOKE THROUGH NAME
```

These grammar rules are wrong (as per Oracle ref above)... fixing them!

**Comment by walter-weinmann** [comment]
Ok - I'l then do the adjustment of the test cases and the railroad diagrams.

**Comment by c-bik** [comment]
Thanks @walter-weinmann Please note that all grammar rules currently implemented are not verified (so not necessarily correct). If you see a rule that doesn't match Oracle reference please give me an issue to fix it.

**Comment by walter-weinmann** [comment]
So the target implementation is Oracle 10g Release 2?

**Comment by c-bik** [comment]
Yes, and with occasional customization (mostly extension) for IMEM as and when needed, but without violating the original rules.

**Comment by walter-weinmann** [comment]
Are you sure about the empty-clause?

```
db_user_proxy -> '$empty'
db_user_proxy -> proxy_with
db_user_proxy -> proxy_auth_req
db_user_proxy -> proxy_with proxy_auth_req
```

Oracle defines:

![image](https://cloud.githubusercontent.com/assets/1956149/13791648/6f0ec6be-eaee-11e5-8322-f990753f1cd7.png)

**Comment by c-bik** [comment]
Its not `proxy_clause` its `db_user_proxy`
![image](https://cloud.githubusercontent.com/assets/913008/13792851/442af426-eaf4-11e5-913e-084998a1edbf.png)

This means `ALTER USER name_user_1 GRANT|REVOKE CONNECT THROUGH` is a complete and valid SQL. Not sure whats that imply!
