### ISSUE TITLE
Fold problem

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/sqlparse#33]
Browse Table gives in ZHH man:

![2016-03-28 21_33_37-zhhapmop-sbsm01 it bwns ch - remote desktop connection - __remote](https://cloud.githubusercontent.com/assets/1941407/14087983/21dacc8c-f52d-11e5-9d22-7b2622ca9a41.png)

Moving back to latest tagged version of sqlparse there until this is fixed.

**Comment by c-bik** [comment]
Unable to re produce in sqlparse:
```erlang
3> {ok, PT} = sqlparse:parsetree("select OBJECT_NAME, GRANTEE, PERMISSION, REVOKE_COMMENT, OBJECT_TYPE, TAG from APP_OBJECT_GRANT").  
{ok,[{{select,[{fields,[<<"OBJECT_NAME">>,<<"GRANTEE">>,
                        <<"PERMISSION">>,<<"REVOKE_COMMENT">>,
                        <<"OBJECT_TYPE">>,<<"TAG">>]},
               {from,[<<"APP_OBJECT_GRANT">>]},
               {where,{}},
               {'hierarchical query',{}},
               {'group by',[]},
               {having,{}},
               {'order by',[]}]},
      {extra,<<>>}}]}
4> sqlparse:pt_to_string(PT).
<<"select  OBJECT_NAME, GRANTEE, PERMISSION, REVOKE_COMMENT, OBJECT_TYPE, TAG from APP_OBJECT_GRANT">>
```

Can you please try this in your VM and confirm?

**Comment by stoch** [comment]
Absence of issue confirmed on ZHH management with above query.

**Comment by stoch** [comment]
Whitespace is not yet "minimalistic"

![image](https://cloud.githubusercontent.com/assets/1941407/14243651/1b2c3be4-fa57-11e5-903f-c2430df23d55.png)


extra whitespace seen after "select" and before "where" and "order by"

**Comment by c-bik** [comment]
Fixed https://github.com/K2InformaticsGmbH/sqlparse/commit/581078a77f455d4c9efeee1fb9546a188f3b9d5b

Please pull sqlparse locally and verify.

**Comment by c-bik** [comment]
IMEM tests are passing as of https://github.com/K2InformaticsGmbH/imem/commit/2e7fb492447f9ce5bb67d242de6b9aa0ea267057#diff-25d902c24283ab8cfbac54dfa101ad31
