### ISSUE TITLE
GROUP BY: Restrictions on the SELECT list

### ISSUE THREAD

**Issue by walter-weinmann** [K2InformaticsGmbH/sqlparse#45]
The following query is illegal:

![image](https://cloud.githubusercontent.com/assets/1956149/15345374/98a363da-1cae-11e6-9ff8-267f4cfe5655.png)

From  the Oracle documentation ([Database SQL Language Reference](https://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_10002.htm#i2065646)):

**Restrictions on the Select List** 
The select list is subject to the following restrictions:

If you also specify a `group_by_clause` in this statement, then this select list can contain only the following types of expressions:

- Constants

- Aggregate functions and the functions USER, UID, and SYSDATE

- Expressions identical to those in the `group_by_clause`. If the `group_by_clause` is in a subquery, then all columns in the select list of the subquery must match the `GROUP BY` columns in the subquery. If the select list and GROUP BY columns of a top-level query or of a subquery do not match, then the statement results in ORA-00979.

- Expressions involving the preceding expressions that evaluate to the same value for all rows in a group

**Comment by c-bik** [comment]
I suppose this restriction can't be enforced by a railroad diagram (grammar). Hence its a DB internal restriction and not a syntax rule.
