### ISSUE TITLE
SQL Parsing fails (missing DBLINK support)

### ISSUE THREAD

**Issue by acautin** [K2InformaticsGmbH/sqlparse#54]
**moved from https://github.com/K2InformaticsGmbH/dderl/issues/338**
SQL does not parse any more, probably since attempt to detect database link @ in table name

```sql
select *
from
    SIS_DS_ADMIN.TAB_MOBILE@SIS.EXASTAG.PIOSCS
  where
    DMO_MSISDN >= :SQLT_STR_MSISDN 
    and
    DMO_MSISDN <= :SQLT_STR_MSISDN_2 
```

Quotes around the whole name are not tolerated by Oracle (name too long) but this works:
```
select *
from
SIS_DS_ADMIN.TAB_MOBILE@ "SIS.EXASTAG.PIOSCS"
where
DMO_MSISDN >= :SQLT_STR_MSISDN
and
DMO_MSISDN <= :SQLT_STR_MSISDN_2
```

@c-bik Question: Can we support fully qualified DB link names without quotes?

**Comment by walter-weinmann** [comment]
Solved by #89.
